version: "3"
services:
  db:
    image: postgres
    tty: true
    restart: always
    container_name: dental-planner-db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dental_db
    ports:
      - 5432:5432
    volumes:
      - dental_planner_data:/var/lib/postgresql/data
    networks:
      - dental_planner_network

networks:
  dental_planner_network:

volumes:
  dental_planner_data:
