version: "3"
services:
  app:
    container_name: dental-planner-api
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    depends_on:
      - postgres
    stdin_open: true
    tty: true

  postgres:
    container_name: dental-planner-db
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
