openapi: 3.0.0
info:
  title: Documentação Dental Planner API
  version: 1.0.0
  description: API para servir app de gestão de clínicas odontológicas
servers:
  - url: http://localhost:3000/api
paths:
  /patients:
    get:
      tags:
        - Pacientes
      summary: Recuperar lista de pacientes
      description: Obter uma lista paginada de pacientes com seus detalhes
      parameters:
        - $ref: "#/components/parameters/query/PageIndex"
        - $ref: "#/components/parameters/query/PerPage"
      responses:
        '200':
          description: Lista de pacientes e metadados de paginação
          content:
            application/json:
              schema:
                type: object
                properties:
                  patients:
                    type: array
                    items:
                      $ref: "#/components/schemas/Patient"
                  pagination:
                    $ref: "#/components/schemas/Pagination"
    post:
      tags:
        - Pacientes
      summary: Cadastrar um novo paciente
      description: Adicionar um novo registro de paciente ao sistema.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewPatientRequest"
      responses:
        '201':
          description: Paciente criado com sucesso
          content: {}
        '400':
          description: Requisição inválida devido a dados incorretos ou faltando.
          content: {}
  /patients/{id}:
    get:
      tags:
        - Pacientes
      summary: Obter detalhes de um paciente
      description: Retorna os detalhes de um paciente pelo seu identificador único.
      parameters:
        - $ref: "#/components/parameters/path/PatientId"
      responses:
        '200':
          description: Detalhes do paciente encontrados.
          content:
            application/json:
              schema:
                type: object
                properties:
                  patient:
                    $ref: "#/components/schemas/Patient"
        '404':
          description: Paciente não encontrado.
    put:
      tags:
        - Pacientes
      summary: Atualizar informações de um paciente
      description: Atualiza os detalhes de um paciente pelo seu identificador único.
      parameters:
        - $ref: "#/components/parameters/path/PatientId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdatePatientRequest"
      responses:
        '200':
          description: Paciente atualizado com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  patient:
                    $ref: "#/components/schemas/Patient"
        '400':
          description: Requisição inválida devido a dados incorretos ou faltando.
        '404':
          description: Paciente não encontrado.
    delete:
      tags:
        - Pacientes
      summary: Excluir um paciente
      description: Remove um paciente do sistema pelo seu identificador único.
      parameters:
        - $ref: "#/components/parameters/path/PatientId"
      responses:
        '204':
          description: Paciente excluído com sucesso. Nenhum conteúdo retornado.
        '404':
          description: Paciente não encontrado.
        '400':
          description: Requisição inválida devido a parâmetros incorretos.

components:
  parameters:
    path:
      PatientId:
        name: id
        in: path
        required: true
        description: Identificador único do paciente (UUID).
        schema:
          type: string
          format: uuid
    query:
      PageIndex:
        name: page_index
        in: query
        required: false
        description: Número da página que deseja buscar.
        schema:
          type: number
          example: 1
      PerPage:
        name: per_page
        in: query
        required: false
        description: Quantidade máxima de itens por página.
        schema:
          type: number
          example: 10
  schemas:
    Patient:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Identificador único do paciente.
        name:
          type: string
          description: Nome completo do paciente.
        date_of_birth:
          type: string
          format: date
          description: Data de nascimento do paciente.
        cpf:
          type: string
          description: CPF (Cadastro de Pessoa Física).
        phone:
          type: string
          description: Número de telefone do paciente.
        email:
          type: string
          format: email
          description: Email do paciente.
        gender:
          type: string
          enum: [male, female, other]
          description: Gênero do paciente.
        created_at:
          type: string
          format: date-time
          description: Data e hora de criação do registro.
    Pagination:
      type: object
      properties:
        page_index:
          type: integer
          description: Índice da página atual.
        total_count:
          type: integer
          description: Número total de pacientes.
        page_items_count:
          type: integer
          description: Número de pacientes na página atual.
    NewPatientRequest:
      type: object
      properties:
        patient:
          type: object
          required:
            - name
            - phone
            - date_of_birth
            - gender
          properties:
            name:
              type: string
              description: Nome completo do paciente.
            phone:
              type: string
              description: Número de telefone do paciente.
            date_of_birth:
              type: string
              format: date-time
              description: Data de nascimento do paciente.
            gender:
              type: string
              enum: [male, female, other]
              description: Gênero do paciente.
            cpf:
              type: string
              description: CPF (Cadastro de Pessoa Física). Pode estar vazio.
            email:
              type: string
              format: email
              description: Email do paciente. Pode estar vazio.
    UpdatePatientRequest:
      type: object
      properties:
        patient:
          type: object
          properties:
            name:
              type: string
              description: Nome completo do paciente.
            phone:
              type: string
              description: Número de telefone do paciente.
            date_of_birth:
              type: string
              format: date-time
              description: Data de nascimento do paciente.
            gender:
              type: string
              enum: [male, female, other]
              description: Gênero do paciente.
            cpf:
              type: string
              description: CPF (Cadastro de Pessoa Física).
            email:
              type: string
              format: email
              description: Email do paciente.
