# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  url: postgres://postgres:postgres@localhost:5432/dental-planner-api_development


test:
  <<: *default
  url: postgres://postgres:postgres@localhost:5432/dental-planner-api_test
