name: Brakeman Scanner

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '.**'
      - '**.md'
      - 'docs/**'
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.**'
      - '**.md'
      - 'docs/**'

jobs:
  brakeman_scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0
          bundler-cache: true

      - name: Install Brakeman
        run: gem install brakeman -v 5.1.1

      - name: Run Brakeman
        run: brakeman
