name: Backend Linter
env:
  RAILS_ENV: test
  RACK_ENV: test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '.**'
      - '**.md'
      - 'docs/**.md'
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.**'
      - '**.md'
      - 'docs/**.md'
jobs:
  back_linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        env:
          BUNDLE_PATH: vendor/bundle
        with:
          ruby-version: 3.3.0
          bundler: "Gemfile.lock"
      - name: Install dependencies
        run: bundle install
      - name: Run Rubocop
        run: bundle exec rubocop
