env:
  RUBY_VERSION: 3.0.3

name: Linter
on:
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '.**'
      - '**.md'
      - 'docs/**.md'
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.**'
      - '**.md'
      - 'docs/**.md'
jobs:
  rubocop-linter:
    name: Rubocop
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: Run Rubocop
        run: bundle exec rubocop
