env:
  RUBY_VERSION: 3.0.3
  RAILS_ENV: test
  RACK_ENV: test

name: Linter
on:
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '.**'
      - '**.md'
      - 'docs/**.md'
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.**'
      - '**.md'
      - 'docs/**.md'
jobs:
  rubocop-linter:
    name: Rubocop
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        env:
          BUNDLE_PATH: vendor/bundle
        with:
          bundler: "Gemfile.lock"
          bundler-cache: true
      - name: Run Rubocop
        run: bundle exec rubocop